# Generated by Django 5.2.7 on 2025-10-15 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('aadhar_number', models.CharField(max_length=12, unique=True)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('taluka', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account_number', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=15)),
                ('bank_name', models.CharField(max_length=100)),
                ('pan_card', models.CharField(max_length=10)),
                ('aadhar_card', models.CharField(max_length=12)),
                ('farmer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='dashboard.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='LandDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_land_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('soil_type', models.CharField(max_length=50)),
                ('ownership_type', models.CharField(max_length=50)),
                ('ownership_proof', models.FileField(blank=True, null=True, upload_to='land_docs/')),
                ('farmer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='land', to='dashboard.farmer')),
            ],
        ),
    ]
