# Generated by Django 5.2.7 on 2025-10-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_landdetail_farmer_bankinformation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landinformation',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='aadhaar_card',
            field=models.FileField(blank=True, null=True, upload_to='documents/aadhaar_cards/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='land_proof',
            field=models.FileField(blank=True, null=True, upload_to='land_proofs/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='land_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ownership_type',
            field=models.CharField(blank=True, choices=[('owned', 'Owned'), ('leased', 'Leased'), ('shared', 'Shared')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to='documents/pan_cards/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='soil_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='unit',
            field=models.CharField(blank=True, choices=[('acre', 'Acre'), ('hectare', 'Hectare'), ('sq_m', 'Square Meter')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='BankInformation',
        ),
        migrations.DeleteModel(
            name='LandInformation',
        ),
    ]
