# Generated by Django 5.2.7 on 2025-10-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_userprofile_aadhaar_number_userprofile_email_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='aadhaar_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mobile_number',
        ),
    ]
