# Generated by Django 5.2.7 on 2025-10-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_userprofile_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
