# Generated by Django 5.2.7 on 2025-10-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_userprofile_aadhaar_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='land_proof',
            field=models.FileField(blank=True, null=True, upload_to='documents/land_proofs/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='documents/profile_photos/'),
        ),
    ]
