# Generated by Django 5.2.7 on 2025-10-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_userprofile_land_proof_alter_userprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bank_account_number',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ifsc_code',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
