# Generated by Django 5.2.7 on 2025-10-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_userprofile_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
