# Generated by Django 5.2.4 on 2025-10-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginSignup', '0002_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('admin', 'Admin'), ('officer', 'Officer'), ('subsidy_provider', 'Subsidy Provider')], default='farmer', max_length=20),
        ),
    ]
